config/routes.rb
Rails.application.routes.draw do
  ## get "[URI]" => "[Controller]#[nome da página]"
  ## get "produtos" => "produtos#index"
  root "produtos#index"
  ## get "/produtos/new" => "produtos#new"
  ## post "/produtos" => "produtos#create"
  ## delete "produtos/:id" => "produtos#destroy", as: :produto
  ## todos os comentados vão ser criados pelo resources
  resources :produtos, only: [:new, :create, :destroy]
  get "/produtos/busca" => "produtos#busca", as: :busca_produto
end

app/models/produto.rb
class Produto < ActiveRecord::Base
	validates :nome, :descricao, :quantidade, :preco,  presence: true
	validates :nome, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
	def index
		## @ serve para dizer que a variável é de instancia e estarão disponívels para visualização em todo o site.
		@produtos_order_nome = Produto.order :nome
		@produtos_order_preco = Produto.order(:preco).limit 2
	end

	def new
		@produto = Produto.new
	end

	def busca
		@nome_da_busca = params[:nome]
		@produtos = Produto.where "nome like ?", "%#{@nome_da_busca}%"
	end

	def create
		## O método require faz a solicitção do produto.
		valores = params.require(:produto).permit :nome, :descricao, :quantidade, :preco
		@produto = Produto.new valores
		if @produto.save
			flash[:notice] = "Produto salvo com sucesso!"
			redirect_to root_url
		else
			render :new
		end
	end

	def destroy
		id = params[:id]
		Produto.destroy id
		redirect_to root_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LojaCamisetas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= nav_bar brand: "XPTO", brand_link: root_url do %>
		<%= form_tag busca_produto_path, method: :get, class: "navbar-form navbar-right" do %>
			<div class="form-group">
				<%= text_field_tag :nome, @nome_da_busca, class: "form-control" %>
				<%= button_to "Buscar", nil, class: "btn btn-default" %>
			</div>
		<% end %>
	<% end %>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/produtos/_produto.html.erb
<tr>
    <td> <%= produto.nome %> </%> </td>
    <td> <%= produto.descricao %> </%> </td>
    <td> <%= produto.preco %> </%> </td>
    <td> <%= button_to "Remover", produto, method: :delete, class: "btn btn-danger", data: { confirm: "Tem certeza que deseja remover?"} %> </td>
</tr>

app/views/produtos/busca.html.erb
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th></th>        
        </tr>
    </thead>
    <tbody>
        <!-- <%= render partial: "produto", collection: @produtos %> descritivo oq o cara de baixo faz -->
        <%= render @produtos %>
    </tbody>
</table>

app/views/produtos/index.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th></th>        
        </tr>
    </thead>
    <tbody>
        <!-- <%= render partial: "produto", collection: @produtos_order_nome %> descritivo oq o cara de baixo faz  -->
        <%= render @produtos_order_preco %>
    </tbody>
</table>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>           
        </tr>
    </thead>
    <tbody>
        <!-- <%= render partial: "produto", collection: @produtos_order_preco %>  descritivo oq o cara de baixo faz  -->
        <%= render @produtos_order_preco %>
    </tbody>    
</table>

<%= link_to "Novo", new_produto_path %>

app/views/produtos/new.html.erb
<% @produto.errors.full_messages.each do |message| %>
	<div class="alert alert-danger" role="alert"><%= message %></div>
<% end %>

<%= form_for @produto do |f| %>
	<div class="form-group">
		<%= f.label :nome %>
		<%= f.text_field :nome, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :descricao %>
		<%= f.text_area :descricao, class: "form-control", rows: 4 %> 
	</div>

	<div class="form-inline">
		<div class="form-group">
			<%= f.label :quantidade %>
			<%= f.number_field :quantidade, step: 1, class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.label :preco %>
			<%= f.number_field :preco, class: "form-control" %>
		</div>
	</div>

		<%= f.submit "Salvar", class: "btn btn-primary" %>
<% end %>